### ISSUE TITLE
How to add pagination to a category page?

### ISSUE THREAD

**Issue by EricBusch** [tighten/jigsaw#479]
Hi

In the [starter blog template](https://github.com/tightenco/jigsaw-blog-template), how would I add post pagination to a category page?

I tried adding this code...

```md
---
pagination:
    collection: posts
    perPage: 4
---
```

..to the [category.blade.php](https://github.com/tightenco/jigsaw-blog-template/blob/master/source/_layouts/category.blade.php) file but that didn't work. The frontmatter just appears at the top of the rendered page. 

**Category Page:**

<img width="621" alt="Screen Shot 2020-07-02 at 3 16 34 PM" src="https://user-images.githubusercontent.com/12106436/86400702-18b70880-bc77-11ea-9b59-c0099f6577bb.png">

Any ideas?

Thanks
Eric

**Comment by EricBusch** [comment]
Just curious... is this even possible? I've been banging my head against this for a couple of days with no luck... 

Thanks!

**Comment by damiani** [comment]
I don't believe it's possible at the moment, since the categories are really a separate collection that references _another_ collection (posts) for its content, and there's no built-in way to paginate that from within the collection config (see https://github.com/tightenco/jigsaw/issues/466)

The way Jigsaw builds these category pages is in need of some improvement. Later this week, I'm going to work on implementing some of the proposals from https://github.com/tightenco/jigsaw/issues/273 and https://github.com/tightenco/jigsaw/issues/272, to make generating tag/category index pages easier; these enhancements would also include support for paginating these groupings of collection items.

**Comment by EricBusch** [comment]
@damiani Thanks for getting back to me so fast! That's great news! I'm really looking forward to it! :)
 
Thanks for all your work on Jigsaw. It's a great framework! 🥇 Keep up the great work!

**Comment by palexandrite** [comment]
I came across with htis issue alse.

Please, let me more about current situation of that.
