### ISSUE TITLE
Deploying to Laravel Vapor?

### ISSUE THREAD

**Issue by 19peaches** [tighten/jigsaw#503]
Any chance the docs can be updated with instructions on deploying to Laravel Vapor?

I've googled quite a bit and can't find anyone deploying a Jigsaw site to Vapor.

**Comment by bakerkretzmar** [comment]
Jigsaw is for building static HTML sites with no database or backend, so Vapor is overkill. I'm not even sure it would be possible since Vapor is specifically for deploying Laravel apps, but Jigsaw isn't one and there's no 'application' to run with a Jigsaw site. You can deploy your site on S3 or Netlify or a similar service, basically all you need is file hosting and DNS.

See [Hosting a static website on Amazon S3](https://docs.aws.amazon.com/AmazonS3/latest/dev/WebsiteHosting.html) and [A Step-by-Step Guide: Deploying A Static Site or Single-page App](https://www.netlify.com/blog/2016/10/27/a-step-by-step-guide-deploying-a-static-site-or-single-page-app/). Jigsaw's docs are hosted on Netlify, take a look at that repo and the `netlify.toml` file for an example of how to set it up: [tighten/jigsaw-site](https://github.com/tighten/jigsaw-site).

**Comment by 19peaches** [comment]
It's not for you to say whether it's overkill or not, my ecosystem contains several Laravel applications on subdomains, but like many, my main domain is a Jigsaw site with a landing page and documentation. 

My purpose for using Vapor is to be able to seamlessly scale, but I didn't realize till I tried to deploy something else that it explicitly requires you to upload a Laravel app. I won't complain to you guys about that here. 

Perhaps I'll just clone the Laravel documentation, that'll give me the same basic result within an actual Laravel app.
