### ISSUE TITLE
webpack.mix.js file location

### ISSUE THREAD

**Issue by willans** [tighten/jigsaw#505]
I typically have all of my build related files (webpack, tailwind etc.) in a single folder in the root directory (usually named build).

In the package.json scripts, you're able to define the webpack.mix.js file location by doing:

`--env.mixfile=build/webpack.mix`

i.e. 

`"dev:webpack": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js --env.mixfile=build/webpack.mix",`

However, doing this results in the following message when running a task like `npm run local`
 
```
Too many arguments, expected arguments "command" "env".  
                                                           
build [--pretty PRETTY] [-c|--cache [CACHE]] [--] [<env>]
```

This means that the Jigsaw build never automatically triggers.

**Comment by bakerkretzmar** [comment]
@willans thanks for reporting this, I had no idea Mix was able to use a `webpack.mix.js` file not in the site root.

It seems this is an issue with how we've set up the environment variables in our `package.json` and in `laravel-mix-jigsaw`. By default, [our build script in this repo includes `--env=local`](https://github.com/tighten/jigsaw/blob/master/stubs/mix/package.json#L4). `laravel-mix-jigsaw` then [pulls this out with `this.env = argv.env || 'local'`](https://github.com/tighten/laravel-mix-jigsaw/blob/main/index.js#L22), which works because when no other `--env` options are passed, `argv.env` will be `'local'`.

However if other `--env` options _are_ passed, things get weird. Laravel Mix expects `argv.env` to be an object, and it looks for `argv.env.mixfile`, which works fine if you only pass `--env.mixfile=build/webpack.mix`. Without `--env=local` though, `laravel-mix-jigsaw` chokes and produces the error you're seeing.

And if you pass _both_ `--env=local` and `--env.mixfile=build/webpack.mix`, `argv.env` ends up as `['local', { mixfile: 'build/webpack.mix' }]` which is of course completely useless.

The permanent solution here will be to: a) change our default build scripts to pass something like `--environment=local` or [maybe `JIGSAW_ENV=local`](https://github.com/JeffreyWay/laravel-mix/commit/c29d2f92456d35b5f92e521f551e089c7f8c94f8), and b) update `laravel-mix-jigsaw` to check for that new argument (we can probably do this in a backwards-compatible way by first checking whether `argv.env` is a string).

I'll do that asap, in the meantime... all I can think of really is to move your `webpack.mix.js` file back into your site root temporarily, which I know is very annoying. Thanks for your patience!
