### ISSUE TITLE
Stripe Checkout Endpoint

### ISSUE THREAD

**Issue by tiansial** [tighten/jigsaw#522]
I'm building a e-commerce project powered by Jigsaw + Prismic + Stripe, but the Stripe Checkout needs a custom endpoint to create a checkout session. Would it be possible to create something like this with just Jigsaw?

**Comment by bakerkretzmar** [comment]
Cool! I think that depends what you need the 'endpoint' to do. If all you need is a URL for Stripe to redirect users back to, yes you can do that, you'd just need to set up a custom collection/entry with that exact URL so that the page exists in your Jigsaw site. If you need to handle more complicated tokens/redirects, it depends. I'm not super familiar with Stripe Checkout, what exactly are the requirements for this endpoint?

**Comment by tiansial** [comment]
The checkout endpoint would build a session with Stripe SDK using some POST data, and return JSON with the session ID.

**Comment by tiansial** [comment]
Right now, my solution would be Netlify Functions, but I really much prefer if I could keep it simple, inside Jigsaw.

**Comment by bakerkretzmar** [comment]
Yes, that should be possible. Take a look at Stripe's examples in [stripe-samples/checkout-one-time-payments](https://github.com/stripe-samples/checkout-one-time-payments). There's an "HTML and Vanilla JS" one in that repo at `client/html` that should work with Jigsaw.
