### ISSUE TITLE
Automatically add id's for Header elements so they can be referenced in anchor tags

### ISSUE THREAD

**Issue by GrimLink** [tighten/jigsaw#545]
It would be nice if there was option to automatically add id's to Header elements in the markdown output.
So it can be referenced via a TOC and via other anchor links.

**Comment by bakerkretzmar** [comment]
As far as I know our markdown parser doesn't support this _automatically_, but you can definitely do it manually with something like this:

```md
## Heading {#heading}
```

There might be extensions/plugins that provide support for this automatically, we'd definitely welcome a PR adding something like this!

See tighten/jigsaw-docs-template#39.

**Comment by GrimLink** [comment]
@bakerkretzmar Don't expect this from me very soon 😅
I am not a PHP developer, but for now the `{#heading}` is a solid solution.
I will try and see if I can do it automatically, later on.

Thx, I will close this for now.

The only thing that would be nice.
If the jigsaw had this it there docs.

**Comment by apepindev** [comment]
For anyone stumbling across this, the markdown parser for content uses [CommonMark](https://commonmark.thephpleague.com/) and you can add extensions via the Jigsaw `config.php`. I got this to work by adding the [Heading Permalink Extension](https://commonmark.thephpleague.com/2.4/extensions/heading-permalinks/).

Just make sure you also include the default extensions from the Jigsaw lib too otherwise they'd get overwritten.

https://github.com/tighten/jigsaw/blob/e43b0ea6afe7ff4b6198f775512372bb294a306a/src/Parsers/CommonMarkParser.php#L24-L29

So you should have this in your `config.php`.

```
use League\CommonMark\Extension\Attributes\AttributesExtension;
use League\CommonMark\Extension\HeadingPermalink\HeadingPermalinkExtension;
use League\CommonMark\Extension\HeadingPermalink\HeadingPermalinkRenderer;
use League\CommonMark\Extension\SmartPunct\SmartPunctExtension;
use League\CommonMark\Extension\Strikethrough\StrikethroughExtension;
use League\CommonMark\Extension\Table\TableExtension;

return [
    ...

    'commonmark' => [
        'config' => [
            'heading_permalink' => [
                'html_class' => 'heading-permalink',
                'insert' => 'after',
                'title' => "Permalink",
                'symbol' => HeadingPermalinkRenderer::DEFAULT_SYMBOL,
            ],
        ],
        'extensions' => [
            new AttributesExtension,
            new SmartPunctExtension,
            new StrikethroughExtension,
            new TableExtension,
            new HeadingPermalinkExtension,
        ],
    ],

    ...
];
```
