### ISSUE TITLE
Build takes 30 minutes (multi-language project)

### ISSUE THREAD

**Issue by scofield-ua** [tighten/jigsaw#546]
Hey. I have a multi-language project with a 2000-2500 pages for each language (5 languages), and it takes about 30 minutes to build everything. Is it a lot of pages for a jigsaw project? If it's a normal behavior then it's fine for me.

I made a test repo where you can test it - https://github.com/scofield-ua/jigsaw-test.
Go to [this file](https://github.com/scofield-ua/jigsaw-test/blob/master/app/src/Data/PageValues.php) to specify number of pages, just change `range(1, 5)` to `range(1, 1000)` for example.

Maybe I'm doing something wrong.

**Comment by damiani** [comment]
That is definitely larger than the average Jigsaw site, yes. You can speed things up a bit by using caching when running your builds: see https://github.com/tighten/jigsaw/pull/260 (which just reminded me that this is undocumented, so I'll add that to the documentation shortly).

We're going to test a bit with your repo—there are some optimizations we can propose to your code, and we'll also see if there are any solvable bottlenecks in the core that could improve build times on such a large site. We'll get back to you shortly with some findings.

**Comment by scofield-ua** [comment]
Thank you, Keith.

I'll try to help a bit with guiding where I think the bottleneck can possible be.

So, on every page (you can call it a post page or whatever) I have "related" content to the page which schematically can look like this:
```
| post
| - related posts (separate file)
| - related links (separate file)
| - other related stuff (separate file)
``` 
I'm including it with a `includeIf` method. And it's different for every single page, and because of this Jigsaw is generating .md and cache files for every file (for a post + related items). 

The possible solution that just came up in my mind — move it from separate files and place it directly in `post` template.

I don't think that cache parameter will help much here, because if I change something in related files then it will have to regenerate everything anyway.

**Comment by bakerkretzmar** [comment]
@scofield-ua this is very interesting, Keith and I will keep looking into it. That is a lot of pages, yes, but 30 minutes is _way_ too long. Thanks a lot for setting that example repo up, it was a huge help. I think there are two things going on here:

**1. `related-page.blade.php`**

Almost the entire build time is taken up by this snippet at the top of `source/related-page.blade.php`:

```php
    $langPages = $relatedPages->filter(function ($item) use ($page) {
        return $item->pageValue === $page->pageValue && $item->lang !== $page->lang;
    });

    $nextPages = $relatedPages->filter(function ($item) use ($page) {
        $minValue = $page->pageValue - 5;
        $maxValue = $page->pageValue + 5;

        if ($item->pageValue === $page->pageValue) {
            return false;
        }

        return ($item->pageValue >= $minValue && $item->pageValue <= $maxValue) && ($item->lang === $page->lang);
    });
```

Because these two `->filter()` operations are in a template, they run every time that template renders, which in this case appears to be at _least_ once on every single page.

The first one is relatively straightforward to only do once, while the collection is being built, but the second one might need more work. I optimized it a bit so it's operating on a smaller Collection instance and running just once per site collection item, but you may be able to improve it further. Here's where I got to:

```php
            // in config.php
            'items' => function () use ($relatedPages) {
                $pages = $relatedPages->getPages();

                $langPages = [];

                $items = collect($pages)->tap(function ($pages) use (&$langPages) {
                    $langPages['en'] = $pages->where('lang', 'en')->keyBy('pageValue');
                    $langPages['fr'] = $pages->where('lang', 'fr')->keyBy('pageValue');
                    $langPages['es'] = $pages->where('lang', 'es')->keyBy('pageValue');
                })->map(function (Page $page) use ($langPages) {
                    $nextPages = $langPages[$page->lang]
                        ->where('pageValue', '!=', $page->pageValue)
                        ->whereBetween('pageValue', [$page->pageValue - 6, $page->pageValue + 6])
                        ->all();

                    return [
                        'title' => $page->getTitle(),
                        'metaTitle' => $page->getMetaTitle(),
                        'metaDescription' => $page->getMetaDescription(),
                        'metaKeywords' => $page->getMetaKeywords(),
                        'slug' => $page->getSlug(),
                        'uniSlug' => $page->getUniSlug(),
                        'lang' => $page->getLang(),
                        'url' => $page->getUrl(),
                        'pageValue' => $page->getPageValue(),
                        // this is neeed to prevent adding english related pages into "en" subfolder
                        'path' => $page->getLang() === "en" ? '{slug}' : '{lang}/{slug}',
                        'langPages' => match ($page->lang) {
                            'en' => [$langPages['es'][$page->pageValue], $langPages['fr'][$page->pageValue]],
                            'fr' => [$langPages['es'][$page->pageValue], $langPages['en'][$page->pageValue]],
                            'es' => [$langPages['en'][$page->pageValue], $langPages['fr'][$page->pageValue]],
                        },
                        'nextPages' => $nextPages,
                    ];
                });

                return $items;
            }
```

Then remove the whole `@php` block from the top of `related-pages.php`, replace `count($langPages)` and `count($nextPages)` with `count($page->langPages ?? [])` and `count($page->nextPages ?? [])`, and make `$lang` and `$pageValue` public in `Page.php`.

**2. Docker**

I don't know a lot about Docker but I have heard that there are filesystem performance issues with it, at least on macOS. This seems to match what I'm seeing locally: with `range(1, 1000)` in your demo, building the site directly on my machine (without the above optimizations) takes 1m4s, and building it in Docker takes 5m28s. So, if possible, _not_ using Docker in this case might speed your build up an additional 5x or so.

**Comment by scofield-ua** [comment]
@bakerkretzmar thank you for a spent time and looking into it, appreciated.

Very nice tip about `$langPages` and `$nextPages`. 

Build took like 12 minutes with all the fixes and using local PHP 8 instead of Docker. 
Since I have 5 languages and 2100 pages for each language I guess it's fine.

**Comment by bakerkretzmar** [comment]
Are you able to give me access to the repo for the real site? I'd be interested in trying to build the whole thing locally with your exact setup.

What kind of computer are you building the site on? I'm still seeing much better performance than that locally, but it might just be hardware at this point.

**Comment by scofield-ua** [comment]
@bakerkretzmar tried to run build command on Github, and it took like 5 minutes (including all the above optimization and NOT using docker). 

I think we can close the issue, since the build time is far less than it was at the beginning. Thank you for your help.

**Comment by bakerkretzmar** [comment]
@scofield-ua sounds good, happy to help! 30min down to 5 is pretty good 😅
