### ISSUE TITLE
Local development with valet

### ISSUE THREAD

**Issue by nathangross** [tighten/jigsaw#549]
Is there a way to modify the npm script to better work with my valet setup? Whenever I run `npm run watch` it will open a browser window to `localhost:3000`. Not a big deal, but it would be nice if it would open to `my-project.test` or whatever I have set in my local `config.php`.

**Comment by bakerkretzmar** [comment]
I've looked into this extensively and as far as I know it isn't possible, no. You can disable the auto-opening by setting BrowserSync's `open` config option to `false`, but you'll need to manually open `my-project.test` (and it won't auto-refresh).

**Comment by nathangross** [comment]
Ah ok, good to know. You can just add `:3000` to the end of your URL and it will auto-refresh. 

Thanks!

**Comment by bakerkretzmar** [comment]
@nathangross this blew my mind I had absolutely no idea you could do that................... amazing!

I re-read the Browsersync docs and I don't think there's a way to automatically open a custom URL unfortunately.

Thanks for using Jigsaw!! 😂

**Comment by jakebathman** [comment]
Hey everyone, I just had to do this on a new project because it was driving me crazy (I also use a non-standard TLD suffix for Valet, hence the stuff at the top with `VALET_DOMAIN`). Figured I'd share the solution if anyone is looking for it.

Here's what you need to add to `webpack.mix.js` to get BrowserSync to use your **secured** Valet site, automatically, when using `npm run watch`. You can omit the `https` stuff if you're not securing your site.

```diff
const mix = require('laravel-mix');
require('laravel-mix-jigsaw');

+ // Default valet hostname guess is repo.test, but you can override
+ // this by setting the VALET_DOMAIN environment variable in a .env file
+ const domain = process.env.VALET_DOMAIN ?? require('path').basename(__dirname) + '.test';
+ const homedir = require('os').homedir();

mix.disableSuccessNotifications();
mix.setPublicPath('source/assets/build');

mix.jigsaw()
    .js('source/_assets/js/main.js', 'js')
    .css('source/_assets/css/main.css', 'css', [
        require('postcss-import'),
        require('tailwindcss'),
    ])
    .options({
        processCssUrls: false,
    })
+    .browserSync({
+        files: ['build_*/**'],
+        proxy: 'https://' + domain,
+        host: domain,
+        listen: domain, // listen is an undocumented option, needed if you're using https and the Browsersync UI
+        open: 'external',
+        https: {
+            key: homedir + '/.config/valet/Certificates/' + domain + '.key',
+            cert: homedir + '/.config/valet/Certificates/' + domain + '.crt',
+        },
+    })
    .version();
```

Running `npm run watch` using this opens `https://my-repo.meow:3000`, and supports automatic build and reload as expected. The Browsersync UI is available at `http://my-repo.meow:3001` (note `http` only, that's a Browsersync thing) and all features also work here as expected.
