### ISSUE TITLE
Docs: Production config overwrites the config file

### ISSUE THREAD

**Issue by adrelliott** [tighten/jigsaw#622]
Is it just the way I'm reading it, but in the docs, it suggests that you can add a filter to the `config.production.php` file.

However, when you add it the way the docs suggest, it overwrites the entire 'collections' key, meaning none of the `collections` config works in production.

The docs suggest:

```
return [
    'baseUrl' => 'https://productionsite.com',
    'production' => true,
    'collections' => [
        'posts' => [
            'filter' => function ($item) {
                return $item->published && ! $item->local;
            }
        ],
];
``` 

Should this documentation suggest, instead, that you add a key, perhaps like this:

```
return [
    'baseUrl' => 'https://oblonghq.com',
    'production' => true,
    'collections' => ['posts']['filter'] =  function ($item) {
        return $item->published && ! $item->local;
    },
];

```

Now I'm not in any way an expert, but this confused me for days! Am I reading it wrongly, or do the docs need to be updated?

:-)

**Comment by adrelliott** [comment]
Having re-read this, clearly, my pseudo-code is complete trash.

But the issue stands: 

**I still have to redefine the entire `collections` key in the `config.production.php` file.**

Am I doing this wrong? Or is that the right way to do this?

**Comment by bakerkretzmar** [comment]
You're not doing it wrong, Jigsaw doesn't merge the config recursively so `collections` gets overwritten.

I can't find that example in our docs, can you link to it? We should definitely update that so it's clearer.

There's actually a PR open right now to add support for something similar, #584. In v2 we will probably merge the config recursively but we can't before then because it would be a huge breaking change.

For now you'd have to copy in the whole `collections` array and just change what's different, or pull your `config.php` into your `config.production.php` and merge them there manually.

**Comment by adrelliott** [comment]
Hi @bakerkretzmar 

Thanks for your speedy reply and advice - totally understand. I will just copy the `collections` key of the config to the production version for now.

The page that got me confused is this one:

https://jigsaw.tighten.com/docs/collections-filtering/

**Comment by bakerkretzmar** [comment]
Thanks, I'll take a look and get that updated. I'm going to close this for now but this is definitely something we're going to address in v2.
