### ISSUE TITLE
permalink doesn't update the path in $page->getUrl()

### ISSUE THREAD

**Issue by roelofjan-elsinga** [tighten/jigsaw#660]
I'm using the permalink key in a file to generate an atom feed at /atom.xml:

```
---
permalink: atom.xml
---
```
This builds the file as it should and I have the file accessible at /atom.xml.

However, the ``$page->getUrl()`` is still rendered as ``https:/mywebsite.com/blog/feed.atom`` rather than using the permalink value.

**Comment by bakerkretzmar** [comment]
`permalink` overrides the path of the output file on disk _after_ templates are rendered and your site is built, so it doesn't change the name and path that Jigsaw uses internally. `$page->getUrl()` and even `$page->getPath()` will still report `feed.atom` because that's the input file name.

Since specifying a permalink basically hard-codes the path and URL of that page, I'd suggest just hard-coding `atom.xml` in your template too.
