### ISSUE TITLE
feature request: allow output extension to be changed from .html

### ISSUE THREAD

**Issue by codemonkeynorth** [tighten/jigsaw#664]
It would be useful to be able to change the output extension from `.html`, in my case to `.php`

I realise it's an edge case but I'm using **jigsaw** to create a temporary static drop-in "holding site" theme for wordpress whilst the main site is being worked on separately

as such being able to generate the files as eg `index.php` and `page-home.php` would be helpful

thanks
J.

(just as a note...  for now i've created an `index.php` that does a `require('index.html')`).. since the `index.php` will be copied over as-is, this works fine for the build)

**Comment by bakerkretzmar** [comment]
If you set a permalink with a `.php` extension does that work? Something like this:

`index.blade.php`
```mdx
---
permalink: index.php
---
{{-- Blade template contents --}}
```

**Comment by jmp909** [comment]
@bakerkretzmar - it does indeed, thank you very much!!

the question now is whether anyone would actually want to output every file with a specific extension as a global build option. possibly yes I guess. 

I'll leave this open for now, but again for my case where I've only got a couple of pages your solution is perfect.

**Comment by codemonkeynorth** [comment]
(posted from the wrong account) @bakerkretzmar thanks

**Comment by bakerkretzmar** [comment]
@codemonkeynorth no problem! I'm going to close this for now but that is an interesting idea. I doubt anyone would need it for their entire site, but I can see it possibly being useful for an entire collection. We could explore making the `path` config option support file extensions, so that they could be configured/overridden there, or adding an `extension` option or something.
