### ISSUE TITLE
`*.blade.php` files in collection folders break stuff

### ISSUE THREAD

**Issue by simonhamp** [tighten/jigsaw#670]
If you don't put at least `@extends(_layouts.your_layout)` in the file, it just breaks everything.

Took me too long to realise this was what was happening because there's no output when this goes wrong :(

**Comment by bakerkretzmar** [comment]
Do you need to have a file called `.blade.php` in your collection folder? Can you explain what breaks exactly, and what you would expect here?

**Comment by husseinalhammad** [comment]
I quickly tested this. It seems to me the blade file is rendered fine, but is not generated in the expected place when it doesn't extend a layout. This is easier to observe when you disable pretty URLs; the generated filename is just the extension `.html` and is saved to the root of `build_*`. 

---

The docs indicate that collection items can be Blade files:

> Collection items can be Markdown or Blade files, or even [Blade/Markdown hybrid](https://jigsaw.tighten.com/docs/content-other-file-types) files.

**Comment by simonhamp** [comment]
> Can you explain what breaks exactly
Everything - if you have a collection 'entry' file that you decide to use `.blade.php` for but you _don't_ make it extend a layout, it's like it overrides all other output whatever URL you look at. If the file is empty (like what I did when I was just starting), that results in just a blank view for every valid page

> and what you would expect here?
I'd expect a little more detail in the docs so if you choose to use a `.blade.php` file, it's clear that you can't just use empty files, you need to configure them.

Even better than that though, would be that this doesn't have this weird side-effect, that you could use any file type at this point and it not completely break the builds.

**Comment by bakerkretzmar** [comment]
Oh I thought you meant one file literally called `.blade.php`. I can't reproduce this, empty Blade files or Blade files that don't `@extend` anything work fine for me in a fresh site. Can you share a repo or more of you site config so I can try to reproduce and debug this?

**Comment by simonhamp** [comment]
Ah, sorry. No I meant any `*.blade.php` files.

> empty Blade files or Blade files that don't @extend anything work fine for me in a fresh site.

Are they in a collection? If you create a collection called `posts` and a collection folder called `_posts` and in that folder place an empty `test.blade.php`... what do you see in the browser for `/index.html`?

**Comment by bakerkretzmar** [comment]
Oof okay yeah it's blank. I'll dig into this, thanks 👍🏻

**Comment by bakerkretzmar** [comment]
@simonhamp thanks again for reporting this. The intended behaviour is that omitting `@extends` renders nothing, because the `extends` metadata is basically how you tell Jigsaw 'this item has a parent template and should be rendered'.

This is mentioned in the docs: https://jigsaw.tighten.com/docs/collections-extending-parent-templates/#collection-items-with-no-parent-template

This makes a bit more sense with Markdown—if the file doesn't have an `extends` then it's basically just data, and you can still use it as a collection item, render it manually (e.g. in a list on another page), etc. but it doesn't automatically render its own page. The same is true for Blade files, which is a bit counter-intuitive because using Blade files as 'data' and not rendering them isn't really a thing.

The bug here (and it's a doozy) is that those Blade collection items are just completely overwriting other pages. I've fixed that and will open the PR in a sec.

Do you have a specific use case in mind here for Blade collection items that _are_ rendered and do _not_ extend a parent template? Why don't you have a layout? One thing that you can do with Markdown files is set `extends` in the collection config so you don't need to repeat it in every file, that's never worked for Blade but we could look into it.
