### ISSUE TITLE
Remote collection nested array returning null in page object

### ISSUE THREAD

**Issue by gregvarghese** [tighten/jigsaw#684]
Hi Tighten team! 

I'm running into a weird issue with nested arrays in collections and I can't find a way to fix it and was hoping someone might have a suggestion. 

I'm using a remote collection and the JSON returns a nested array with 3 values. When I map the collection, everything appears to be correct but when I try to use it in the page, the page object returns 3 null values for the object. 

JSON from remote API: 

```
{"stats":[
{"label":"AVG EMAIL CTR PER CAMPAIGN","value":".9%"},
{"label":"FACEBOOK AD CTR GROWTH","value":"2X"},
{"label":"INCREASE IN AVG REVENUE PAST 6 MONTHS","value":"38%"}
],
"title":"Title",
```

config.php to return the title and values:

```
$collection = collect($projects->data)->map(function ($project) {
                return [
                    'title' => $project->title,
                    'stats' => $project->stats,
                    ];
            });
                return $collection;
            }
```

Adding Ray to the config shows the collection item:

```
"title": "Title",
"stats":[3 items
0:{2 items
"label":string"AVG EMAIL CTR PER CAMPAIGN"
"value":string".9%"
}
1:{2 items
"label":string"FACEBOOK AD CTR GROWTH"
"value":string"2X"
}
2:{2 items
"label":string"INCREASE IN AVG REVENUE PAST 6 MONTHS"
"value":string"38%"
}
]
```

When I try to use the object in the page, I get the error:
`Attempt to read property "value" on null` 

Inspecting the page object with Ray app shows:
```
"title" => "Title",
"stats" => array:3 [▼
      0 => null
      1 => null
      2 => null
    ]
```

Am I doing something wrong or is this a bug?

Any insight would be much appreciated! Thanks!

**Comment by bakerkretzmar** [comment]
How are you fetching `$projects->data` and how _exactly_ are you accessing the data in your template? Can you include the code where you're trying to access `->value` and getting that error? If possible can you also include the complete code snippets you're using to send data to Ray, and screenshots of what's coming through? The formatting of the Ray dump you included makes it hard to understand exactly what it is.

Off the top of my head this looks like it could just be that you're calling `json_decode(...)` instead of `json_decode(..., true)` somewhere, and so your data is coming back as PHP objects instead of nested arrays. Or maybe the opposite, and it's an array and you need to do `$stat['value']` instead of `$stat->value`.

**Comment by gregvarghese** [comment]
Hi @bakerkretzmar , 

Thanks for the quick reply. 

Here's the code from config.php where I pull the remote API. It's a secure URL with secure auth token so I could not include it but it does return the JSON above. 

 ```
'projectstats' => [
            'extends' => '_layouts.project',
            'items' => function ($config) {

                $context = stream_context_create(array(
                    'http' => array(
                        'header'  => "X-AUTH-TOKEN: $token"
                    )
                ));

                $projects = json_decode(file_get_contents('secure_url', true, $context));

                $collection = collect($projects->data)->map(function ($project) {

                    return [
                        'title' => $project->title,
                        'stats' => $project->stats,
                        'path' => '{collection}/{name}',
                    ];
                });

                ray($collection)->label('Project with Stats');
                return $collection;
            }
        ],
```

In the page, here's how I'm viewing the page object with Ray:

`@php(ray($page)->label('Project Page'))`

Displaying it in the page is just stacking it in a div right now:

```
                        <div class="stats">
                            @php(ray($stats)->label('Stats Count'))
                            @foreach($stats as $stat)
                                <p>{{ $stat->value }}</p>
                                <p>{{ $stat->label }}</p>
                            @endforeach
                         </div>

```

Screenshot of Ray for both the collection from config and page variable (sensitive info was blacked out) showing that stats are null on the page object:

<img width="1024" alt="ray-684" src="https://user-images.githubusercontent.com/12222172/236842056-ad14987c-14ec-4430-9d20-4d9bd63cc018.png">

I checked another collection with a nested array of image urls and confirmed it's exhibiting the same behavior. I hadn't created the page last night when I submitted the ticket which is why I'm mentioning it now.

Please let me know if I can provide any additional information to help troubleshoot.

**Comment by gregvarghese** [comment]
Hi @bakerkretzmar, just wanted to follow up on this issue. Do you need any more information from me?

**Comment by bakerkretzmar** [comment]
@gregvarghese looks like this is because Symfony's YAML component doesn't dump objects by default, it needs to be passed the `Yaml::DUMP_OBJECT_AS_MAP` flag. I'm not sure how risky adding that to Jigsaw core is but we'll look into it.

For now if you set `json_decode()`'s `$associative` parameter to true (`json_decode(..., true)`) all your data will come back as arrays and your code should work fine.

**Comment by bakerkretzmar** [comment]
No problem, and definitely not a waste of time! The YAML object dumping thing is something we should look at more closely so I'm glad you made me find it 😄
